import type { Character } from "@/lib/types";

export const RUKHSAR_RU_FIXTURE: Character = {
  id: "fixture-rukhsar-ru",
  makerId: "fixture-maker",
  name: 'Rukhsar "Ru" Ansari',
  archetype: "rebel",
  tagline: "She can sell certainty while hiding the cost.",
  personality: "A quick, watchful operator whose jokes keep fear one step behind.",
  voiceGender: "androgynous",
  voiceDesc: "Primary spoken language: English in the character's explicitly stated UK or Irish dialect. androgynous, adult. Studio quality. Persona: rebel. Performance direction: low South London register with Urdu family rhythm, dry timing, and compressed urgency. Clean close-mic signal.",
  sfxDesc: "Premium cinematic Foley one-shot for Rukhsar: Five seconds: a coin snaps, then five coins chatter, followed by a buckle strike, after that a cloth scrape, next a heel lands. Blend close detail into one coherent event. No sequence.",
  themeDesc: "Original 2020s dark cinematic bass character theme. Fully arranged and mastered. Arrangement: bowed strings enter. Payoff: she discovers the mission was a lie. Avoid: generic loops, muddy low end, thin percussion. About 12 seconds, ends cleanly, no fade-out. Instrumental only, no vocals.",
  avatarHue: 345,
  licenseType: "paid",
  royaltyRate: 30,
  createdAt: "2026-07-26T00:00:00.000Z",
  stats: { castings: 0, fans: 0, earnings: 0 },
  productionBible: {
    version: 1,
    creationInputs: {
      characterBrief: "Ru, a 22-year-old South London courier.",
      visualFormat: "live action",
      appearanceBrief: "22-year-old South Asian woman",
      worldBrief: "South London at night",
      archetypes: ["rebel"],
      voiceDirection: "low South London register with Urdu family rhythm, dry timing, and compressed urgency",
      signatureSfxDirection: "one old coin snaps against the brass pouch clasp",
      themeDirection: "tense contemporary bass with a small bowed-string identity",
      licenseType: "paid",
      royaltyRate: 30,
    },
    dramatic: {
      externalWant: "deliver the evidence before dawn",
      innerNeed: "trust one person with the truth",
      contradiction: "speed disguises careful moral judgment",
      stakes: "the wrong delivery exposes her family",
      vulnerability: "kindness interrupts her prepared exit",
      moralBoundary: "never trades another courier's safety for speed",
    },
    performance: {
      restingExpression: "closed-mouth half-smile",
      underPressure: "one breath, then a precise decision",
      signatureGesture: "thumbs one old coin at her hip",
      movementStyle: "economical forward motion",
      eyeline: "maps exits before faces",
      tempo: "dry, quick setup and compressed landing",
    },
    visual: {
      perceivedAge: "22-year-old South Asian woman",
      medium: "live-action cinematic photograph",
      recognitionLocks: [
        "chipped left canine visible in a full grin",
        "close-set upward brows",
        "mole under the right lower lip",
        "old coin-pouch belt low at the hips",
      ],
      faceAnchors: ["close-set upward brows", "mole under the right lower lip"],
      hair: "black shoulder-length curls",
      wardrobe: "maroon kurta, olive salwar, old coin-pouch belt low at the hips, worn flip-flops",
      silhouette: "compact and forward-leaning",
      palette: ["maroon", "olive", "brass"],
      continuityRules: ["same face and age", "same hair", "same closed wardrobe set"],
    },
    cinematography: {
      heroFraming: "chest-to-knee casting portrait",
      cameraHeight: "eye level",
      lens: "50mm",
      keyLight: "soft sodium key from frame left",
      fillLight: "cool street bounce",
      edgeLight: "small wet edge",
      worldTexture: "wet brick, bus glass, old brass",
    },
    story: {
      hookPattern: "the package opens before she delivers it",
      escalationPattern: "every shortcut reveals a witness",
      cliffhangerPattern: "the buyer uses her childhood name",
      payoffPattern: "she delivers the evidence to its victim",
      recurringMotifs: ["old coins", "bus windows"],
      avoid: ["generic courier montage"],
    },
  },
};

